'use strict';
const resource = require('../lib/Resource');
console.log(resource.getIp());
console.log(resource.getCpuCount());
console.log(resource.getFreeMem());
console.log(resource.getHomeDir());
console.log(resource.getTotalMem());
console.log(resource.getHostname());
console.log(resource.getOsType());
console.log(resource.getTempDir());